# 1. Usuário padrão do container MySQL
spring.datasource.username=root

# 2. Senha definida no seu docker-compose (MYSQL_ROOT_PASSWORD)
spring.datasource.password=1234

# 3. URL de conexão
# localhost:3306 funciona porque você mapeou as portas no docker ("3306:3306")
spring.datasource.url=jdbc:mysql://localhost:3306/db_empresa?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC

# 4. Dialeto (Para MySQL 8+)
# Altere de MySQL8Dialect para apenas MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 5. Mostrar SQL no console (Útil para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 6. Estratégia de atualização do banco
# 'update' altera as tabelas existentes.
# 'none' é recomendado se você quiser que APENAS o seu script init.sql controle a estrutura.
spring.jpa.hibernate.ddl-auto=update