server.port=8000
spring.application.name=keywords
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.url=jdbc:h2:file:./db_keywords
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true